name: Build and Test

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    name: OS=${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    env:
      ICDIR: ../xzintbit
      MSBASICDIR: ../msbasic
      FUNCTESTDIR: ../6502_65C02_functional_tests

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
      - name: Checkout vm6502
        uses: actions/checkout@v4
        with:
          path: vm6502

      - name: Checkout xzintbit
        uses: actions/checkout@v4
        with:
          repository: matushorvath/xzintbit
          path: xzintbit

      - name: Build xzintbit
        working-directory: xzintbit
        env:
          CC: gcc
        run: make build-vm

      - name: Checkout Microsoft Basic
        uses: actions/checkout@v4
        with:
          repository: matushorvath/msbasic
          path: msbasic

      - name: Install cc65
        run: |
          if [ "$RUNNER_OS" == "Linux" ]; then
            sudo apt install -y cc65
          elif [ "$RUNNER_OS" == "Windows" ]; then
            choco install cc65-compiler
          elif [ "$RUNNER_OS" == "macOS" ]; then
            brew install cc65
          fi
        shell: bash

      - name: Build Microsoft Basic
        working-directory: msbasic
        run: ./make.sh
        shell: bash

      - name: Checkout 6502 functional tests
        uses: actions/checkout@v4
        with:
          repository: Klaus2m5/6502_65C02_functional_tests
          path: 6502_65C02_functional_tests

      - name: Build
        working-directory: vm6502
        run: make build
        shell: bash

      - name: Test
        working-directory: vm6502
        run: make test

      - name: Store artifact
        uses: actions/upload-artifact@v4
        with:
          name: msbasic.input
          path: vm6502/bin/msbasic.input
          if-no-files-found: error
        if: github.ref == 'refs/heads/main' && matrix.os == 'ubuntu-latest'
